### ISSUE TITLE
Fix line height and font size for article titles 

### ISSUE THREAD

**Issue by apreshill** [rstudio/hugo-tourmaline#18]
<img width="1159" alt="Screen Shot 2020-04-04 at 3 33 19 PM" src="https://user-images.githubusercontent.com/12160301/78462862-3205e400-768b-11ea-9d45-22fe42dda96f.png">

**Comment by dcossyleon** [comment]
Looks like this was solved by https://github.com/rstudio/hugo-tourmaline/pull/28
