### ISSUE TITLE
Anchorize headers

### ISSUE THREAD

**Issue by apreshill** [rstudio/hugo-tourmaline#38]
https://gohugo.io/getting-started/configuration-markup#heading-link-example

**Comment by apreshill** [comment]
```
<!--https://gohugo.io/getting-started/configuration-markup#heading-link-example-->
<!--icon from material design: https://material.io/resources/icons/?style=baseline-->


<h{{ .Level }} id="{{ .Anchor | safeURL }}">{{ .Text | safeHTML }}<a href="#{{ .Anchor | safeURL }}"><svg class="anchor-symbol" height="26" width="26" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
<path d="M0 0h24v24H0z" fill="currentColor"></path>
<path d="M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76.0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71.0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71.0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76.0 5-2.24 5-5s-2.24-5-5-5z"></path>
</svg></a>
</h{{ .Level }}>
```

https://github.com/rbind/apreshill/blob/27e1cbe80a83e3498461e64f764de18524f1b1a9/layouts/_default/_markup/render-heading.html#L1-L8

**Comment by dcossyleon** [comment]
@apreshill, I think I added the code for this in [the right spot](https://github.com/rstudio/hugo-tourmaline/pull/43/commits/843a3cb89fbbd79fd8bc2be6c75841c6545477d2), but the little anchors don't seem to be rendering (e.g. see headers [here](https://deploy-preview-43--tourmaline.netlify.app/learn/statistics/bootstrap/) ). 

Any ideas what I might be doing wrong?

**Comment by apreshill** [comment]
And you added CSS too? Here was mine:

```
/*---anchor headings-- */

a > svg.anchor-symbol {
  color: transparent;
  margin-bottom: .5rem;
  margin-left: .5rem;
  fill: #1a162d99;
}

a > svg.anchor-symbol:hover {
  fill: #06805E;
  transition: fill 0.6s ease;
}
```

https://github.com/rbind/apreshill/blob/ca78236d9d61e8fe6618d9b2a6eb40bc4bcab4c1/assets/scss/custom.scss#L347-L359

If yes, let me take a longer look and think on this some!

**Comment by dcossyleon** [comment]
@apreshill Yep, all anchor-related CSS here: https://github.com/rstudio/hugo-tourmaline/blob/desiree-CSS/static/css/main-site.css#L2015-L2053

**Comment by apreshill** [comment]
OK let me think on it!!

**Comment by apreshill** [comment]
Placing it here, this was a Hugo version issue: we bumped locally and on Netlify: https://gohugo.io/getting-started/configuration-markup#markdown-render-hooks

v.71.0
